# Mongo
MONGO_DEFAULT_URI = "mongodb://localhost:27017"
MONGO_URI_ENV_VAR = "MONGO_URI"
MONGO_DEFAULT_DB = "scraping_db"
MONGO_DB_ENV_VAR = "MONGO_DB"
MONGO_SCRAPED_COLLECTION = "scraped_items"
MONGO_DEFAULT_MAX_CONNECTIONS_COUNT = 10
MONGO_MAX_CONNECTIONS_COUNT_ENV_VAR = "MONGO_MAX_CONNECTIONS_COUNT"
MONGO_DEFAULT_MIN_CONNECTIONS_COUNT = 2
MONGO_MIN_CONNECTIONS_COUNT_ENV_VAR = "MONGO_MIN_CONNECTIONS_COUNT"
